/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author braul
 */
public class VistaVotacion extends javax.swing.JFrame {

    /**
     * Creates new form VistaVotacion
     */
    public VistaVotacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        botonP1 = new javax.swing.JButton();
        botonP3 = new javax.swing.JButton();
        botonP2 = new javax.swing.JButton();
        labelTotalNaranja = new javax.swing.JLabel();
        textoTotalP1 = new javax.swing.JTextField();
        labelTotalNaranja1 = new javax.swing.JLabel();
        textoTotalP2 = new javax.swing.JTextField();
        labelTotalNaranja2 = new javax.swing.JLabel();
        textoTotalP3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setText("¡Vota por un producto!");

        botonP1.setText("Producto1");
        botonP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonP1ActionPerformed(evt);
            }
        });

        botonP3.setText("Producto3");
        botonP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonP3ActionPerformed(evt);
            }
        });

        botonP2.setText("Producto2");
        botonP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonP2ActionPerformed(evt);
            }
        });

        labelTotalNaranja.setForeground(new java.awt.Color(0, 0, 0));
        labelTotalNaranja.setText("Total:");

        textoTotalP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTotalP1ActionPerformed(evt);
            }
        });

        labelTotalNaranja1.setForeground(new java.awt.Color(0, 0, 0));
        labelTotalNaranja1.setText("Total:");

        textoTotalP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTotalP2ActionPerformed(evt);
            }
        });

        labelTotalNaranja2.setForeground(new java.awt.Color(0, 0, 0));
        labelTotalNaranja2.setText("Total:");

        textoTotalP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTotalP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonP3)
                            .addComponent(botonP1)
                            .addComponent(botonP2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTotalNaranja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoTotalP1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTotalNaranja1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoTotalP2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTotalNaranja2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoTotalP3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonP1)
                    .addComponent(labelTotalNaranja)
                    .addComponent(textoTotalP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonP2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTotalNaranja1)
                        .addComponent(textoTotalP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonP3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTotalNaranja2)
                        .addComponent(textoTotalP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonP1ActionPerformed

    private void botonP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonP3ActionPerformed

    private void botonP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonP2ActionPerformed

    private void textoTotalP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTotalP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTotalP1ActionPerformed

    private void textoTotalP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTotalP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTotalP2ActionPerformed

    private void textoTotalP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTotalP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTotalP3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVotacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonP1;
    public javax.swing.JButton botonP2;
    public javax.swing.JButton botonP3;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTotalNaranja;
    private javax.swing.JLabel labelTotalNaranja1;
    private javax.swing.JLabel labelTotalNaranja2;
    private javax.swing.JTextField textoTotalNaranja;
    private javax.swing.JTextField textoTotalNaranja1;
    public javax.swing.JTextField textoTotalP1;
    public javax.swing.JTextField textoTotalP2;
    public javax.swing.JTextField textoTotalP3;
    // End of variables declaration//GEN-END:variables
}
